name: "Espressif IoT Development Framework (ESP-IDF)"
description: "This action build your firmware for ESP32 directly in GitHub using Espressif ESP-IDF Docker image."
branding:
  color: red
  icon: wifi
inputs:
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    required: false
    default: ''
  action:
    description: 'Action to run inside the docker container (default: builds the project).'
    required: false
    default: 'idf.py build'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.action }}
